### ISSUE TITLE
Create Compendium for fillable objective forms

### ISSUE THREAD

**Issue by alerickblade** [Reaver01/ryuutama#22]
Create pages or modify existing PDFs to be fill-able for objectives.  These are for the GM to build the adventures.  Scenarios come in the following types:
Fight
Gather
Travel

[scenario_target_gathering_v1.01.pdf](https://github.com/Reaver01/ryuutama/files/4571329/scenario_target_gathering_v1.01.pdf)
[scenario_target_travelv1.01.pdf](https://github.com/Reaver01/ryuutama/files/4571330/scenario_target_travelv1.01.pdf)
[scenario target_fight_v1.01.pdf](https://github.com/Reaver01/ryuutama/files/4571331/scenario.target_fight_v1.01.pdf)

**Comment by Reaver01** [comment]
This is better handled with Foundries native journals
