### ISSUE TITLE
Create Scenario Cultivation Sheet

### ISSUE THREAD

**Issue by alerickblade** [Reaver01/ryuutama#23]
Create page or modify existing PDF to be fill-able for GMs to create a timeline for their scenarios.  Example filled out sheet is found on page 161 in the PHB.

[scenario_cultivation.pdf](https://github.com/Reaver01/ryuutama/files/4571342/scenario_cultivation.pdf)

**Comment by Reaver01** [comment]
This is better handled with Foundries native journals
