### ISSUE TITLE
Create Town and World Creation Sheet compendium

### ISSUE THREAD

**Issue by alerickblade** [Reaver01/ryuutama#24]
Create a space or modify existing PDFs to be fill-able for Town Creation Sheets and World Creation Sheets.  GMs use these to track aspects of the towns and worlds, and they are filled out with the help of the players, typically.  Perhaps make them sharable handouts, but only modifiable by the GM?

[town_creation.pdf](https://github.com/Reaver01/ryuutama/files/4571371/town_creation.pdf)
[world_creation.pdf](https://github.com/Reaver01/ryuutama/files/4571372/world_creation.pdf)

**Comment by Reaver01** [comment]
This is better handled with Foundries native journals
