### ISSUE TITLE
Ryuutama Character Sheet Issues

### ISSUE THREAD

**Issue by Miaradz** [Reaver01/ryuutama#50]
Abstract: Level-up tab in the character sheet does not reflect level-up choices made.

Foundry Version: 0.6.2
Ryuutama 0.4.7

What I did: Created a sandbox, with minimal modules, none affecting character sheets. Created a sample character to test sheet capability. Input 100XP to get to level 2 to test leveling up mechanism.

What went wrong: Inputting either HP, MP or choosing the Stat Increase did not accurately reflect in the topside stat boxes. Inputting 1200XP to get to Level 4 showed that that Level 4 stat increase was not reflected either. The favoured terrain choice did not reflect specialty bonus either, and Immunity choice had no mechanical effect. 

Semi-critical issue: Attacker Type taken again does not allow for an extra weapon mastery.

Non-critical issue: Given that many skill checks are paired with another skill, sometimes it feels a little odd to see to chat boxes and having to tabulate success from there, rather than a single read out, but I understand it does make character sheet coding simpler. Also I'm unclear on the checkboxes that increment the Stat up one die level.

![image](https://user-images.githubusercontent.com/66564401/83974177-f05d1800-a91d-11ea-91fc-a8f8f44bb3c6.png)

**Comment by Reaver01** [comment]
Fixed in 0.5.0 release. I removed level reference from the system template.json since it's already there in the form of the key, and forgot to change it in the actor.js to just use key.
