### ISSUE TITLE
Concentration

### ISSUE THREAD

**Issue by Miaradz** [Reaver01/ryuutama#55]
1. Concentration bonuses cannot be applied without editing the skill necessary;  For instance, Concentrating for a Bow shot, the item must be edited manually. Is the design decision therefore to add the bonus manually or to let the GM handle the added concentration bonus? Is there any automation possible? Concentration toggle perhaps?

**Comment by Reaver01** [comment]
![image](https://user-images.githubusercontent.com/1864450/84187020-a9bb0b00-aa4e-11ea-8be2-c5a2d9b04ac6.png)

How does this look? If the player holds ctrl and clicks a check this will pop up. If they don't have fumble points, the option to use them/both doesn't show.

**Comment by Reaver01** [comment]
Done in 3166233
