### ISSUE TITLE
Status Effects always in effect no matter Condition

### ISSUE THREAD

**Issue by Ralegun** [Reaver01/ryuutama#56]
The Status Effects are adjusting the stat even if the Condition has a larger number. It should only take happen if the Condition is a lower than the Status Effect.
![FoundryVTT_2020-08-22_22-50-10](https://user-images.githubusercontent.com/70087280/90972142-6f98cb80-e4cb-11ea-8e2d-0944f3832fab.png)

**Comment by Reaver01** [comment]
#57 fixes this issue
