### ISSUE TITLE
Can't put items in containers on an animal

### ISSUE THREAD

**Issue by bblonski** [Reaver01/ryuutama#59]
As far as I can tell there is no way to put items in a container that is loaded on a pack animal.  I can kinda fake it by setting the size of containers that are carried by pack animals to 0, but then I have to manually manage which containers are loaded on which animals.

**Comment by Reaver01** [comment]
Currently as pack animals are just containers listed as pack animals. I will have to come up with a way to rewrite the already complicated container code to support this. Currently I do not have the time to look through this, but it will be added to a backlog.
