### ISSUE TITLE
Misc Character Info

### ISSUE THREAD

**Issue by alerickblade** [Reaver01/ryuutama#6]
Make a simple modifiable table where players can input their character's descriptive data, as well as certain passive information.  Should include a spot for:

Mastered Weapon (can be drop down, but Fighter type has 2 options, Noble has 2 options, and Noble Fighters have 3 options.  can be same option to confer +1 stacking bonus)

Specialized Terrain (can be drop down)

Personal Item (open text field)

Image Colour/Appearance (large box for this)

Hometown/Reason to travel (large box for this)

Notes (Large box for this)

**Comment by Reaver01** [comment]
Mastered weapons handled in Level tab, and on the Weapon Grace class feature.
Specialized Terrain drop down on the Level tab, check-boxes next to the terrain/weather (display only) to show what is selected.
There is a Description tab that has a large text input for Personal Item/Image/Appearance/Hometown and other misc character info the player wants to write down. 
I don't think there needs to be additional fields for descriptive stuff.
Notes should be handled by journal entries. GM can make journal entries for each player and make them owners.
